aniyomiorg/aniyomi

app/src/main/AndroidManifest.xml
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt

Added picture in picture support (no button support for playing and pausing yet). Closes #170. [Video showcase here.](https://cdn.discordapp.com/attachments/847160899847585833/912672453577285672/21-11-23-05-53-50.mp4)

Add picture in picture mode

---

app/src/main/java/eu/kanade/tachiyomi/ui/anime/episode/EpisodeHolder.kt

A simple QOL to add an Hour part to the Episode Progress when it goes above 60 minutes
Example:-

Add Hour timer to Episode Porgress

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/Gestures.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/res/layout/player_activity.xml

Changes
---
- Add lock and unlock icons to the player UI
- The unlock icon hides the usual player UI
- Double tap and Scroll Gestures return false when player is locked
Images
---
Unlocked player (bottom left)
Locked player (top left)

Add option to lock and unlock controls in mpv player

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/res/layout/player_controls.xml

Changes
---
- Removes a redundant Linear Layout in the player activity xml
- Fixes a bug with status bar showing up and staying when re-entering the player

Minor player fixes

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt

Changes
---
- Fix a bug wherein the player tried to access an mpv property while destroyed, leading to the app closing completely

Fix app closing on pressing back

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/Gestures.kt
app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsPlayerController.kt
app/src/main/res/values/strings.xml

Added an option called Disable in "double-tap to skip length" where if you set it to disable it will not skip the video but instead play/pause the video regardless of where on the screen you double-tap.

Add option to disable double-tap seek

---

app/src/main/java/eu/kanade/tachiyomi/ui/anime/AnimeController.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt
app/src/main/java/eu/kanade/tachiyomi/ui/recent/animehistory/AnimeHistoryController.kt
app/src/main/java/eu/kanade/tachiyomi/ui/recent/animehistory/AnimeHistoryPresenter.kt
app/src/main/java/eu/kanade/tachiyomi/ui/recent/animeupdates/AnimeUpdatesController.kt
app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
app/src/main/res/menu/updates_episode_selection.xml
app/src/main/res/values/strings.xml

Changes
---
- Fix non - downloaded episodes not being parsed properly when sent to external players
- Add external player override to
- Updates
- History
- Added change player option to Updates
- Option to change player now hides when selecting multiple episodes in
- Library
- Updates
- Fix a bug with accessing manga and anime from History , by closing the parent Tab Controller

External player fixes

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt

Changes
---
- Limit the aspect ratio of PiP if it goes too high or too low

Fix PiP aspect ratio, crashing the app

---

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt
app/src/main/res/layout/player_controls.xml
app/src/main/res/values/strings.xml

Changes
---
- Added option to invert the time shown in the playback position text
- Add strings that show up as player information when changing the view mode of the player
- Fixed auto-play moving too fast and sometimes skipping unseen episodes
- Fixed a few more bugs regarding PiP
- PiP now doesn't close when the device's screen is switched off
- Locks and hides controls immediately upon pressing the button to prevent misinputs and UI errors
- Fixed "No ___ Episode" toasts randomly showing up when changing episodes
Images
---
Inverted playback position text :
Different view mode strings :
| Fit | Crop | Stretch |
| ------- | ------- | ------- |
| ![Screenshot_20220526-191724](https://user-images.githubusercontent.com/36792807/170470331-266350f0-c529-44fa-a6f0-584df64490b1.png) | …

Few QOLs and bug fixes

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt

I would like this simple thing in the player that player UI will be hidden from the start of the player.
I tested a few scenarios, seem fine.
I am not sure if hideControls() is in right place though, tell me if I have to move it up or down.

Player UI hidden on player startup

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt
app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsPlayerController.kt
app/src/main/res/values/strings.xml

* Mainly fixes the problem with external players not playing well with the last seen position for seen episodes. When it's 0L the external apps don't seem to register it and end up using their internal systems. Credit: @Quickdesh
* On older devices where PiP is not supported back button was not working so right now making pipOnExit off by default till it's fixed.
* Changed two strings

Fix for external players lastSeenPosition problem

---

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt
app/src/main/res/layout/player_controls.xml

Before this PR there were two options:
* Elapsed time & Total time
* Remaining time & Total time
Now there is another option:
* Elapsed time & Remaining time
I have made it so that only one of these configurations will be displayed at a time. So before you could switch between `Elapsed time & Total time` & `Remaining time & Total time` now you can switch between `Elapsed time & Total time`, `Remaining time & Total time` or `Elapsed time & Remaining time`.
If you think it will be good to have this feature then please merge this PR.

Option to either invert elapsed time or total time with remaining time

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerPresenter.kt

First things first, I wrote code that just made sense to me. It works, but I don't believe it is the most efficient way to go about it. So Jmir, it would be helpful if you could go through the code and point out/fix stuff that could work better
The problem is that when saving progress it searches for a global ***currentEpisode***, but sometimes the ***currentEpisode*** changes by the time it can update leading to problems when moving forward or back in episodes.
This code is a simple workaround to it!
Changes
---
- Episode progress now updates within the next and previous episode functions
- Said functions now accept position and duration to pass on to progress
- Episode progress also accepts the current episode prior to it being updated

Fix progress saving properly

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt

This will let let aniyomi launch vlc on android 13 but watch state is not saved becasue of an issue in vlc. 
It is already fixed by this [commit](https://code.videolan.org/videolan/vlc-android/-/commit/fad03ab5feec9a33bc4f32ea43f865eb60aa159c) and should start saving watched state starting from the next vlc update. hopefully :)

Fix vlc not launching on api 33

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt

Currently if aniskip doesn't provides intro, but provides other types such as recap, aniyomi will just ignore all the other types. With this pull request, it will show the appropriate skip type whenever it appears and show the +85 second button otherwise.

Aniskip: Show other types even if intro is not detected

---

source-api/build.gradle.kts

Sometimes it dosen't recognise the commonMain in source-api. This is a workaround so there are no problems with further coding. Is taken from a Tachiyomi commit

Import of a multiplatform workaround

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt
app/src/main/res/layout/player_controls.xml
i18n/src/main/res/values/strings-aniyomi.xml

Adds an option to seek through chapters with media controls. If the video provides a separate chapter for opening for example, skipping opening with media controls will be faster, more reliable, and more convenient compared to existing methods.

feat(player): add option for chapter seeking using media controls

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
i18n/src/main/res/values/strings-aniyomi.xml

When there's no chapters available, and "Seek chapters with media controls" is enabled, the skip intro button will be invoked. Slight rephrase to prevent ugly text overflowing.
Also adds animations for actions taken using next/previous with media controls

feat(player): add intro skip for media controls

---

app/src/main/java/eu/kanade/presentation/entries/anime/AnimeScreen.kt

Since completed anime obviously don't have a next episode, there's no point in showing the next airing item. Helps if the source splits up an entry differently from the tracker.

feat(animescreen): don't show "airing in" for completed anime

---

app/src/main/java/eu/kanade/tachiyomi/ui/browse/anime/extension/details/AnimeExtensionDetailsScreenModel.kt

The "info" button and "changelog" button now opens the correct github link

fix(extension-info) fix github links for readme & changelog

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDownloadScreen.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt
i18n/src/main/res/values/strings-aniyomi.xml
i18n/src/main/res/values/strings.xml

Also increases the number of parallel downloads to 5.
The reason for this change is to mitigate traffic for sources that self-host in some way or another. While the number of sources that self-host isn't crazy high, I believe it's high enough to justify this change.

feat(downloader): restrict parallel downloads to unmetered sources

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt

Adds Web Video Caster to the external player preference. Since not all external players uses the same Intents, `getIntentForPackage` can be used to customize the intent for specific players.

feat(player): add Web Video Caster to external player preference

---

app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt

Fixes crash when external player is called on an empty video list, or if the extension throws an exception. Adds some subtitles to external players that supports it.

Fix crash for external players + add subs

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/AdvancedPlayerSettingsScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt
i18n/src/main/res/values/strings-aniyomi.xml

Added the option to modify input.conf to allow users to assign different keyboard buttons to different player functions for mpv
tested this feature on waydroid and my phone with a keyboard attached with a usb-a to usb-c adapter which worked fine for the most part

feat(player): Add support for editing input.conf (closes #1163)

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/GestureHandler.kt

If the player is locked, it shouldn't bring up the screenshotsheet on a long press

feat(player): don't bring up screenshotsheet if player is locked

---

app/src/main/java/eu/kanade/presentation/more/storage/CumulativeStorage.kt
app/src/main/java/eu/kanade/tachiyomi/ui/storage/CommonStorageScreenModel.kt
app/src/main/java/eu/kanade/tachiyomi/ui/storage/anime/AnimeStorageScreenModel.kt
app/src/main/java/eu/kanade/tachiyomi/ui/storage/manga/MangaStorageScreenModel.kt
i18n/src/main/res/values/strings-aniyomi.xml

closes #1191 
Hidden categories are controlled in the storage settings by the hidden category toggle.

fix(storage-viewer): don't show hidden categories in all view

---

core-metadata/src/main/java/tachiyomi/core/metadata/tachiyomi/ChapterDetails.kt
core-metadata/src/main/java/tachiyomi/core/metadata/tachiyomi/EpisodeDetails.kt
source-local/src/androidMain/kotlin/tachiyomi/source/local/entries/anime/LocalAnimeSource.kt
source-local/src/androidMain/kotlin/tachiyomi/source/local/entries/manga/LocalMangaSource.kt

Needs an `episodes.json` file in the same place as everything else

feat(localanime): allow for custom episode data

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/StreamsCatalogSheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/VideoChaptersSheet.kt

fixes this
https://github.com/aniyomiorg/aniyomi/assets/54363735/f13100a3-907b-4dd2-8d45-954a6d52f802
and changes this
https://github.com/aniyomiorg/aniyomi/assets/54363735/d1abd11e-21d7-4b93-8c36-7375aa450c82

fix(player): make chapters sheet scrollable + adjust scrolling in streams sheets

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDownloadScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsMainScreen.kt

Making the ordering or Anime and Manga related items consistent in settings
In Downloads (Download ahead): ![image](https://github.com/aniyomiorg/aniyomi/assets/5874051/3420f49a-2e59-4400-ac6b-d0badb9d0987)
In Library (Chapter Swipes): 
In Main Settings (Player then Reader):

refactor: Make ordering of items consistent

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDownloadScreen.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/manga/MangaDownloader.kt
domain/src/main/java/tachiyomi/domain/download/service/DownloadPreferences.kt
i18n/src/commonMain/resources/MR/base/strings-aniyomi.xml

Implemented a speed limiter for mp4 downloads using okio Throttler class, will overshoot the target initially if a lot of threads are enabled.
Partially closes #157 since ffmpeg downloads will not be limited

feat: Add a setting to throttle downloads

---

app/src/main/java/eu/kanade/domain/extension/anime/interactor/CreateAniyomiExtensionRepo.kt
app/src/main/java/eu/kanade/domain/extension/manga/interactor/CreateMangaExtensionRepo.kt

Automatically convert urls like `https://github.com/user/repo/blob/repo/index.min.json` into `https://raw.githubusercontent.com/user/repo/repo/index.min.json` , helps if user inputs the wrong url.

feat(browse): convert github urls

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/subtitle/SubtitleSettingsSheet.kt

Use the font in mpv-android's assets directory instead of `Typeface.SANS_SERIF` since that can be affected with system customization
If your changes are visual, please provide images below:
| Before | After |
| ------- | ------- |
| ![Screenshot_20240116-214402](https://github.com/aniyomiorg/aniyomi/assets/54363735/1af4190f-1d1c-4dc5-8c59-22810b160cad) | ![Screenshot_20240116-214446](https://github.com/aniyomiorg/aniyomi/assets/54363735/2db1bb10-40cb-4c85-b02f-a126974d81fc) |

Use the font available in mpv's assets instead of system's

---

app/src/main/java/eu/kanade/presentation/entries/anime/components/AnimeEpisodeListItem.kt
app/src/main/java/eu/kanade/presentation/entries/manga/components/MangaChapterListItem.kt

fix: separator when scanlator exists

---

app/src/main/java/eu/kanade/presentation/entries/anime/EpisodeOptionsDialogScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerViewModel.kt
source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/animesource/model/Video.kt

Inspired by #1250
This could be useful when always play externally is on and internal player is needed for a single episode. This is currently possible in the bottom sheet episode menu.

feat(episode-options): add play internally option

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/about/AboutScreen.kt

I have added the toast extension function on the Context to display a toast message with the appropriate string resource whenever the OS is too old for new updates or there are no new updates.
fixes #1298

Fixed update_check_no_fixed new_updates pop up not working #1298

---

app/src/main/java/eu/kanade/domain/ui/model/NavStyle.kt
app/src/main/java/eu/kanade/tachiyomi/data/coil/TachiyomiImageDecoder.kt
app/src/main/java/eu/kanade/tachiyomi/ui/history/HistoriesTab.kt
app/src/main/java/eu/kanade/tachiyomi/ui/updates/UpdatesTab.kt
gradle/libs.versions.toml
i18n/src/commonMain/resources/MR/base/strings.xml

Also bumps the tachiyomi image-decoder dependency since builds were failing with the old version
closes #1512

feat(navigation): add the ability to move browse tab to the more tab

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/PlayerSettingsSheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/PlayerEnums.kt
i18n/src/commonMain/resources/MR/base/strings.xml

As the title suggests, this PR adds a setting that allows users to change what audio channels the player should use.
currently there are only for options: Auto, Mono, Stereo and Reverse Stereo.
can be changed through Settings -> Player -> Audio channels
like so
| In the settings | in the player settings sheet |
| ------- | ------- |
| ![image](https://github.com/aniyomiorg/aniyomi/assets/54363735/baf9473d-c522-40d4-b5e0-f94395326e6d)|![image](https://github.com/aniyomiorg/aniyomi/assets/54363735/a6eea0a9-ec16-4ab4-93a1-95e79148215d) |

feat(player): add audio channels settings

---

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/PlayerEnums.kt
i18n/src/commonMain/resources/MR/base/strings.xml

reference: [mpv documentation](https://mpv.io/manual/master/#options-audio-channels)

Add auto-safe as (default) audio channel

---

app/src/main/java/eu/kanade/domain/extension/manga/interactor/CreateMangaExtensionRepo.kt
app/src/main/java/eu/kanade/tachiyomi/extension/manga/api/MangaExtensionApi.kt

If the support channel in discord is anything to go by, having this repo added as default just leads to people who don't know anything about self-hosting attempting to use these extensions, which they shouldn't. Besides, the extensions in the repo are being updated maintained elsewhere so even if you are using these extensions, using them from this repo doesn't make much sense

feat(repo): remove default manga repo

---

app/src/main/java/eu/kanade/tachiyomi/data/track/jellyfin/Jellyfin.kt
app/src/main/java/eu/kanade/tachiyomi/data/track/jellyfin/JellyfinApi.kt
app/src/main/java/eu/kanade/tachiyomi/data/track/jellyfin/JellyfinInterceptor.kt

I broke enhanced tracking by removing the api key from the url, so now it will go through the source's preferences instead. Old urls will still work

Fix enhanced tracking for jellyfin

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/report_issue.yml
.github/ISSUE_TEMPLATE/request_feature.yml
README.md

Removes mentions of official extension repositories in issue templates and the readme.md.
The extension repo itself will be removed in my mihon merge, so there's no point in removing it now.

[skip ci] feat(github): Remove mentions of official ext repo

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/subtitle/SubtitleSettingsSheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/subtitle/VideoFiltersPage.kt
i18n/src/commonMain/moko-resources/base/strings.xml

As the title suggests it adds video filters, which are:
- Brightness
- Saturation
- Gamma
- Contrast
- Hue
closes #1670 
only caveat I found from my testing was that Saturation and Hue did not work on `gpu` but worked ok on `gpu-next`
https://github.com/user-attachments/assets/4f2a6831-03c6-4a83-9f28-647572ab1597

feat(player): video filters

---

app/src/main/java/eu/kanade/presentation/more/settings/Preference.kt
app/src/main/java/eu/kanade/presentation/more/settings/PreferenceItem.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/AdvancedPlayerSettingsScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt
app/src/main/java/eu/kanade/tachiyomi/util/SubtitleSelect.kt
i18n/src/commonMain/moko-resources/base/strings.xml

* Adds options to allow for blacklisting/whitelisting certain keywords from subtitle name
* Will now correctly select subtitle based on app's language
Partly inspired by https://github.com/CogentRedTester/mpv-sub-select

feat(player): Add better auto sub select

---

app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloadCache.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloadManager.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/manga/MangaDownloadCache.kt

fix(downloader): dont invalidate anime downloads on startup

---

data/src/main/java/tachiyomi/data/category/anime/AnimeCategoryRepositoryImpl.kt
data/src/main/java/tachiyomi/data/category/manga/MangaCategoryRepositoryImpl.kt

categories' hidden flag got reset after deleting/reordering.
1. Go to Settings/Categories screen
2. Hide any category
3. Try deleting any other category or Try reordering categories
The hidden categories should stay hidden
All categories become un-hidden

fix: hidden categories got reset after delete/reorder

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt

After some tests, I found out it was always the changed lines that threw `ConcurrentModificationException`.
Making `isLoadingEpisode = false` unreachable.
Which in turn made `onSecondReached` always return in the first line, so the seen flag was never updated to true.

Fix episode progress not being saved

---

app/src/main/java/eu/kanade/presentation/components/DateText.kt
app/src/main/java/eu/kanade/presentation/history/anime/AnimeHistoryScreen.kt
app/src/main/java/eu/kanade/presentation/history/anime/AnimeHistoryScreenModelStateProvider.kt
app/src/main/java/eu/kanade/presentation/history/manga/MangaHistoryScreen.kt
app/src/main/java/eu/kanade/presentation/history/manga/MangaHistoryScreenModelStateProvider.kt
app/src/main/java/eu/kanade/tachiyomi/ui/history/anime/AnimeHistoryScreenModel.kt
app/src/main/java/eu/kanade/tachiyomi/ui/history/manga/MangaHistoryScreenModel.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/dialogs/EpisodeListDialog.kt
app/src/main/java/eu/kanade/tachiyomi/util/lang/DateExtensions.kt

Changes 
---
- Fixed misuse of LocalDateTime instead of LocalDate within History UI
- History no longer has continuous duplication of date headers
- Does ***not*** affect the "$ Hours Ago" and "$ Minutes Ago" text for chapter/episode releases

fix: History date header duplication

---

app/src/main/java/eu/kanade/presentation/more/MoreScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/Preference.kt
app/src/main/java/eu/kanade/presentation/more/settings/PreferenceItem.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsSearchScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/player/PlayerSettingsAdvancedScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/player/PlayerSettingsAudioScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/player/PlayerSettingsDecoderScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/player/PlayerSettingsGesturesScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/player/PlayerSettingsMainScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/player/PlayerSettingsPlayerScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/screen/player/PlayerSettingsSubtitleScreen.kt
app/src/main/java/eu/kanade/presentation/more/settings/widget/EditTextPreferenceWidget.kt
app/src/main/java/eu/kanade/tachiyomi/ui/more/MoreTab.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/PlayerEnums.kt
app/src/main/java/eu/kanade/tachiyomi/ui/setting/PlayerSettingsScreen.kt
app/src/main/java/mihon/core/migration/migrations/EnumsMigration.kt
app/src/main/java/mihon/core/migration/migrations/Migrations.kt
app/src/main/java/mihon/core/migration/migrations/VideoPlayerPreferenceMigration.kt
i18n/src/commonMain/moko-resources/base/strings.xml

`versionCode` wasn't bumped because no release has been made since the last mihon merge.
Player settings has been moved out into it's own menu because
1. Less clutter
2. Later, preferences with custom screens will be added

Move preferences to prepare for switching to mpvkt

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/GestureHandler.kt

Fixes gesture seeking not working when dragging too fast to the start or end of a video

Fix gesture seeking not seeking to start and end

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerViewModel.kt

Sometimes `onSecondReached` is called before `duration.update{...}`, which marks the episode as seen when just opening the video

Fix episode being marked as seen at start

---

app/src/main/java/eu/kanade/presentation/entries/anime/components/BaseAnimeListItem.kt
app/src/main/java/eu/kanade/presentation/entries/manga/components/BaseMangaListItem.kt
app/src/main/java/eu/kanade/presentation/library/anime/AnimeLibraryList.kt
app/src/main/java/eu/kanade/presentation/library/anime/AnimeLibraryPager.kt
app/src/main/java/eu/kanade/presentation/library/anime/AnimeLibrarySettingsDialog.kt
app/src/main/java/eu/kanade/presentation/library/components/CommonEntryItem.kt
app/src/main/java/eu/kanade/presentation/library/manga/MangaLibraryList.kt
app/src/main/java/eu/kanade/presentation/library/manga/MangaLibraryPager.kt
app/src/main/java/eu/kanade/presentation/library/manga/MangaLibrarySettingsDialog.kt
i18n/src/commonMain/moko-resources/base/plurals.xml
i18n/src/commonMain/moko-resources/base/strings.xml

Added a size slider for the List Display Mode. It uses the same size variable as Grids do to determine size. However, the size of the List gets interpreted not as \<number\> of columns per row, but rather as \<number\> of entries of the list visible on the screen at once ([images 1](https://github.com/user-attachments/assets/ba5e0599-3c97-4184-b3eb-8170022ed518) [and 2](https://github.com/user-attachments/assets/dc641ef7-96e9-4287-982e-e339782aba46)). The default value is set to be 7 for the List. 
The style of the List was changed: the cover is of Book resolution to match the Grids and for better visibility ([image 4](https://github.com/user-attachments/assets/d3cc87ab-1208-4f8f-870b-6af179cc9ec3)).
Other two lists ([browse list](https://github.com/user-attachments/assets/2bdb5784-f7a6-44 …

feat(ui): size slider for the List Display Mode (Closes #1894)

---

app/build.gradle.kts
app/src/main/java/mihon/core/migration/migrations/Migrations.kt
app/src/main/java/mihon/core/migration/migrations/PEMFileMigration.kt

I'm not sure how or why, but something goes wrong when updating the mpv-lib, causing users to get a malformed .pem file and being unable to play anything. We just need to remember to bump the app version whenever we update mpv-lib, or we could copy over the .pem file every time a video is loaded.

feat(migrations): Remove `cacert.pem` on version bump

---

app/src/main/java/eu/kanade/presentation/browse/anime/BrowseAnimeSourceScreen.kt
app/src/main/java/eu/kanade/presentation/browse/anime/components/BrowseAnimeSourceList.kt
app/src/main/java/eu/kanade/presentation/browse/manga/BrowseMangaSourceScreen.kt
app/src/main/java/eu/kanade/presentation/browse/manga/components/BrowseMangaSourceList.kt
app/src/main/java/eu/kanade/presentation/library/components/CommonEntryItem.kt
app/src/main/java/eu/kanade/presentation/library/manga/MangaLibrarySettingsDialog.kt
app/src/main/java/eu/kanade/tachiyomi/ui/browse/anime/source/browse/BrowseAnimeSourceScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/browse/anime/source/browse/BrowseAnimeSourceScreenModel.kt
app/src/main/java/eu/kanade/tachiyomi/ui/browse/manga/source/browse/BrowseMangaSourceScreen.kt
app/src/main/java/eu/kanade/tachiyomi/ui/browse/manga/source/browse/BrowseMangaSourceScreenModel.kt

I came to the conclusion that setting number 7 as the default wouldn't be ideal. Some people might've enjoyed the original list because it would scale with their phone UI if they changed it. I now made the default to be a set value like both the migration list and browse list. It doesn't take away any options because users can just put 7 themselves on the slider. And it's faithful to the previous list.
it's a 3 line change, guys. I hope someone can find some time to merge this in.
(fixup to 2b1dbc18789bfb7018e8ae41c6b7665ed4c3e433)
Edit: well... it's a bit more than 3 lines now, but it now fixes a glitch where the browse list didn't scale like the library list does.

fixup(ui): make the default list a set size and make browse list scale

---

app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt

Save state to bundle to restore upon exiting the external player. Even if it somehow fails to save to the bundle, it will just do nothing instead of crashing the app

fix(external-player): Prevent crash on app death

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt

Closes #1882
Sometimes it will still hang when exiting the player, causing the app to be unresponsive for a short while (which I have no why it's happening) but now it won't at least cause an ANR.

fix(player): Don't run unnecessary stuff when exiting the player

---

app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/anime/model/AnimeDownload.kt

Sometimes, ffmpeg doesn't want to execute the log callback which prevents the progress from being updated so we use the statistics callback instead. This won't help if ffprobe also decides to not send logs, but I haven't managed to figure out a fix for that.

Small fix for downloader + code cleanup

---

app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/PlayerSheets.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/sheets/AudioTracksSheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/sheets/ChaptersSheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/sheets/GenericTracksSheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/sheets/MoreSheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/sheets/QualitySheet.kt
app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/sheets/SubtitleTracksSheet.kt
i18n/src/commonMain/moko-resources/base/strings.xml

Changes
---
- Added titles to player sheets
- Chapters
- Subtitles
- Audio
- Qualities 
- Shifted Audio and Subtitle actions upwards, inline with title
- Updated colours and text to match the actions in the More sheet

UI: add titles to player sheets + consistency with More sheet

---

.github/renovate.json5
app/build.gradle.kts
buildSrc/settings.gradle.kts
core/common/build.gradle.kts
gradle/androidx.versions.toml
gradle/aniyomi.versions.toml
gradle/libs.versions.toml
settings.gradle.kts
source-local/build.gradle.kts

Since dependencies gets bumped from mihon, there's no point in telling renovate to check for updates for those packages.

feat(renovate): Only check for aniyomi-specific libs

---

CHANGELOG.md
app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloadNotifier.kt
app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt
app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadsTab.kt
i18n-aniyomi/src/commonMain/moko-resources/base/strings.xml

Closes #2086
Use async execution of ffmpeg for easier handling of cancellations. Adds back pause/resume button, but with a changed name to better reflect what it actually does.

feat(downloader): Use async execution of ffmpeg

---

CHANGELOG.md
app/src/main/java/eu/kanade/domain/entries/anime/model/Anime.kt
domain/src/main/java/tachiyomi/domain/entries/anime/model/Anime.kt
domain/src/main/java/tachiyomi/domain/library/service/LibraryPreferences.kt

Changes
---
- Fixed setting default settings for the ext lib 16 parameters
- Fixed filtering of fillermarked items
- Added changelog for #1982
- Used wrong commit name by accident (for first commit)

fix: ext lib 16 parameter addition fixes
