aniyomiorg/aniyomi

app/build.gradle.kts, app/src/main/java/eu/kanade/tachiyomi/Migrations.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListInterceptor.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/OAuth.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/OrientationType.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/res/drawable/ic_stay_current_landscape_24dp.xml, app/src/main/res/drawable/ic_stay_current_portrait_24dp.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
=> Sanitize source download folder name (fixes #4945)

app/src/main/java/eu/kanade/tachiyomi/ui/browse/BrowseController.kt
=> text alignment//jmir tutorial

app/src/main/java/eu/kanade/tachiyomi/animesource/AnimeSource.kt, app/src/main/java/eu/kanade/tachiyomi/animesource/AnimeSourceManager.kt, app/src/main/java/eu/kanade/tachiyomi/animesource/LocalAnimeSource.kt, app/src/main/java/eu/kanade/tachiyomi/animesource/model/Link.kt, app/src/main/java/eu/kanade/tachiyomi/animesource/online/AnimeHttpSource.kt, app/src/main/java/eu/kanade/tachiyomi/animesource/online/AnimeHttpSourceFetcher.kt, app/src/main/java/eu/kanade/tachiyomi/animesource/online/ParsedAnimeHttpSource.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/AnimeDownloader.kt, app/src/main/java/eu/kanade/tachiyomi/extension/util/AnimeExtensionLoader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/watcher/EpisodeLoader.kt, app/src/main/java/tachiyomi/animesource/AnimeSource.kt, app/src/main/java/tachiyomi/animesource/model/Video.kt, app/src/main/java/tachiyomi/animesource/model/VideoInfo.kt
This probably won't compile because other parts of the app aren't compatible
=> [Proposal] Lib version 12: mirror Video to Page

app/src/main/res/drawable/anim_animelibrary_enter.xml, app/src/main/res/drawable/anim_animelibrary_leave.xml, app/src/main/res/drawable/ic_animelibrary_filled_24dp.xml, app/src/main/res/drawable/ic_animelibrary_outline_24dp.xml, app/src/main/res/drawable/ic_animelibrary_selector_24dp.xml, app/src/main/res/menu/main_nav.xml
=> animate anime lib icon

app/src/main/java/eu/kanade/tachiyomi/animesource/LocalAnimeSource.kt
=> Fix LocalAnimeSource.

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
Fixes issues with immersive mode in the internal player. 
Closes #341 
Closes #199
=> Fix system bars in internal player

app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsPlayerController.kt
Added support for [MPV remote application](https://github.com/husudosu/mpv-remote-app). I made a short video about the change.
[Youtube link](https://www.youtube.com/watch?v=oPu8AGnOlWY)
=> MPV remote support

app/src/main/java/eu/kanade/tachiyomi/data/database/AnimeDatabaseHelper.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/AnimeDownloadCache.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/AnimeDownloadManager.kt, app/src/main/java/eu/kanade/tachiyomi/extension/api/AnimeExtensionGithubApi.kt, app/src/main/java/eu/kanade/tachiyomi/extension/util/AnimeExtensionInstallActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/animeextension/details/AnimeExtensionDetailsController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/animesource/AnimeSourceController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/animesource/AnimeSourcePresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/animesource/globalsearch/GlobalAnimeSearchController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBrowseController.kt
Changes
---
- Remove redundant History Mapping from Anime Database
- Fixed Anime Extension update checks + changed references of the files from the manga to the anime versions for more consistency
- Fixed anime sources
- Referenced **pinned** sources to the respective anime pinned preference
- Referenced **disabled** sources to the respective anime disabled preference
- Fixed an error with **Last used** anime source not showing up
- Fixed a conflict between the local manga and anime sources
=> Small Changes on Anime side

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
Changes
---
- Fixes a small bug in PiP to prevent multiple player windows from opening up
=> Fix smol PiP bug

app/src/main/java/eu/kanade/tachiyomi/ui/player/Gestures.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/res/layout/player_activity.xml
Changes
---
- Condenses a few functions down to one
- Fixes a couple of player control highlights when clicked
- Add double tap to pause and play
- Fix a bug with player controls auto fading when paused
- Fix a visual bug with the negative brightness bar
- Clean up some code here and there
=> Minor mpv-player UI fixes

.github/ISSUE_TEMPLATE/request_feature.yml
=> quick fix to request_feature.yml

app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/EpisodeBackupPutResolver.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/EpisodeKnownBackupPutResolver.kt, app/src/main/java/eu/kanade/tachiyomi/ui/animelib/AnimelibController.kt, app/src/main/res/menu/animelib_selection.xml
Changes
---
- Fixed a bug with backup not restoring "seen" endpoint of an episode
- Fixed a bug with the wrong bottom bar showing up when selecting anime while in its library
=> Couple of library fixes

app/src/main/java/eu/kanade/tachiyomi/data/backup/full/models/BackupEpisode.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/EpisodeBackupPutResolver.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/EpisodeKnownBackupPutResolver.kt, app/src/main/java/eu/kanade/tachiyomi/ui/animelib/AnimelibController.kt, app/src/main/res/menu/animelib_selection.xml
Changes
---
- Add a method for the backup and restore to properly save "total seconds" of an episode
=> Backup and restore total seconds of an episode

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt
Changes
---
- Fixed a long time bug of status and navigation bars showing up without a swipe
- PiP play/pause button gets properly updated when forced by an external app
=> Even more player bug fixes

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt
Changes
---
- Fix multiple recent windows being created due to a PiP bug in lower android versions
=> Fix multi recent windows

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt, app/src/main/java/eu/kanade/tachiyomi/util/CrashLogUtil.kt, app/src/main/res/drawable/ic_skip_next_56dp.xml, app/src/main/res/drawable/ic_skip_previous_56dp.xml, app/src/main/res/layout/player_activity.xml, app/src/main/res/layout/player_controls.xml
Changes
---
- Rewritten player_controls.xml to fit everything in just one Constraint Layout
- Made Landscape and Portrait consistent with one another
- Removed redundant double commands for landscape and portrait orientations
- Cleaned up the code and the layouts
- Renamed crash logs to aniyomi_crash_logs, as it should be
=> More player updates

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/res/layout/player_controls.xml
Updating max value of Volume bar as some devices have max volume value other than 15
Partial fix for #619
=> Setting maxVolume as volume bar's max value

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt
Changes
---
- Check for whether the device supports PiP before performing actions
=> Fix auto Pip for non supported devices

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
=> Fix autoplay not starting from beginning of episode

app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt, app/src/main/res/drawable/ic_play_pause_bg.xml, app/src/main/res/layout/player_activity.xml
Changes
---
- Increased size of double tap play/pause icon by 11%
- Forced swipe behavior to system bars
- Calls resetControlsFade after skip intro button is tapped
- Added a check for player status before seeking
- Added an mpv-android specific check to mark episodes as watched
=> Minor bug fixes

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
=> Force hiding system bars on rotation

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/Gestures.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerOptionsSheet.kt, app/src/main/res/layout/player_options_sheet.xml, app/src/main/res/values/strings.xml
Changes
---
- Add a toggle to disable Volume and Brightness Gestures
- Add a toggle to disable Horizontal Seek Gesture
=> Add new toggles for gestures

app/src/main/java/eu/kanade/domain/DomainModule.kt, app/src/main/java/eu/kanade/domain/anime/interactor/SetAnimeViewerFlags.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/models/Anime.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerControlsView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsPlayerController.kt, app/src/main/res/layout/player_controls.xml, app/src/main/res/layout/pref_skip_intro_length.xml, app/src/main/res/values/strings.xml
Changes
---
- Add custom lengths
- Improve the look of the button slightly
=> Improve Skip Intro

CONTRIBUTING.md
Changes
---
- Change tachiyomi links to their respective aniyomi ones
=> Aniyomify CONTRIBUTING.md

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
Changes
---
- Seekbar now initialises at the right point
- Skip intro button now only works once the text on it is displayed
=> Smol seeking fixes

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/network/NetworkHelper.kt, app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt, app/src/main/java/eu/kanade/tachiyomi/network/interceptor/UserAgentInterceptor.kt, app/src/main/java/eu/kanade/tachiyomi/source/online/HttpSource.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt, app/src/main/res/values/strings.xml
=> Make default user agent string configurable

app/src/main/java/eu/kanade/presentation/animebrowse/AnimeExtensionDetailsScreen.kt, source-api/consumer-proguard.pro
Changes
---
- Fixes Anime sources not registering
=> Anime Sources Fix

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/util/AniSkipApi.kt
=> fix in aniskip

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDownloadScreen.kt, app/src/main/java/eu/kanade/tachiyomi/data/animedownload/AnimeDownloader.kt, core/src/main/java/eu/kanade/tachiyomi/core/provider/AndroidDownloadFolderProvider.kt
https://user-images.githubusercontent.com/80992641/201793392-78399511-0240-406e-b8f0-6a3abd39e53b.mp4
=> Support for ADM

.github/ISSUE_TEMPLATE/config.yml
Some links were not showing while opening an new issue, this fixes that
=> Fix for issue template

app/src/main/java/eu/kanade/domain/track/service/TrackPreferences.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/anime/AnimeController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/anime/AnimePresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt, i18n/src/main/res/values/strings.xml
Changes
---
- Adds option to auto open tracking sheet when adding an item to the library
=> Add auto open tracking sheet option

app/src/main/java/eu/kanade/tachiyomi/data/notification/Notifications.kt
=> Fix Notification Downloader code

app/src/main/java/eu/kanade/domain/library/service/LibraryPreferences.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/animelib/AnimelibScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/animelib/AnimelibTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/animesource/browse/BrowseAnimeSourceScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryTab.kt, i18n/src/main/res/values/strings-aniyomi.xml, i18n/src/main/res/values/strings.xml
Changes
---
- Fix library titles based on bottom bar option
- Add separate options for Anime and Manga columns in library grid
=> A couple of library changes

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsBrowseScreen.kt
Changes
---
- Remove the extra group
- Fix string used for anime toggle
- Swap their positions
=> Fix browse settings

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/MigrateAnimeSearchScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt, i18n/src/main/res/values/strings-aniyomi.xml
( To be pulled after https://github.com/jmir1/aniyomi/pull/903 )
Changes
---
- Title
=> Option to remember Volume and Brightness

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerViewModel.kt, app/src/main/java/eu/kanade/tachiyomi/util/AniSkipApi.kt
=> Pip and aniskip fixes

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerOptionsSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerTracksSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerViewModel.kt
Changes
---
- Fix a UI bug with loading circle
- Fix the wrong episodes updating their metadata
- Fix skip intro not updating in the player
- Fix Save Image and Set Cover results not sending information to the user
- Clean up the code to remove all `delicate API` warnings
=> Player Fixes

app/src/main/java/eu/kanade/tachiyomi/ui/player/CustomSeekBar.kt
=> Aniskip timestamp patch

app/src/main/java/eu/kanade/domain/ui/model/AppTheme.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/delegate/ThemingDelegate.kt, app/src/main/res/values-night/color_cloudflare.xml, app/src/main/res/values-night/color_doom.xml, app/src/main/res/values-night/color_matrix.xml, app/src/main/res/values-night/color_sapphire.xml, app/src/main/res/values/color_cloudflare.xml, app/src/main/res/values/color_doom.xml, app/src/main/res/values/color_matrix.xml, app/src/main/res/values/color_sapphire.xml, app/src/main/res/values/themes.xml, i18n/src/main/res/values/strings.xml
=> feat(themes): add 4 new themes

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/report_issue.yml, .github/ISSUE_TEMPLATE/request_feature.yml, .github/workflows/build_push.yml, CONTRIBUTING.md, README.md, app/src/main/java/eu/kanade/presentation/browse/anime/AnimeExtensionsScreen.kt, app/src/main/java/eu/kanade/presentation/more/MoreScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/AboutScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/anime/AnimeLibraryUpdateNotifier.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/manga/MangaLibraryUpdateNotifier.kt, app/src/main/java/eu/kanade/tachiyomi/data/updater/AppUpdateChecker.kt, app/src/main/java/eu/kanade/tachiyomi/extension/anime/api/AnimeExtensionGithubApi.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/anime/extension/details/AnimeExtensionDetailsScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/manga/extension/details/MangaExtensionDetailsScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/manga/migration/sources/MigrateMangaSourceTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/anime/AnimeLibraryTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/manga/MangaLibraryTab.kt
=> chore: change repo links to aniyomiorg (#1035)

app/src/main/java/eu/kanade/domain/entries/anime/interactor/SetAnimeViewerFlags.kt, app/src/main/java/eu/kanade/presentation/entries/EntryScreenConstants.kt, app/src/main/java/eu/kanade/presentation/entries/anime/AnimeScreen.kt, app/src/main/java/eu/kanade/presentation/entries/anime/components/AnimeEpisodeListItem.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupAnime.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/models/anime/Anime.kt, app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/AnimeScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/AnimeScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/util/AniChartApi.kt, domain/src/main/java/tachiyomi/domain/entries/anime/model/Anime.kt
Changes
---
- Track the anime through Anilist or Mal to get the next episode countdown
=> feat(anime screen): Next Episode Countdown 

app/src/main/java/eu/kanade/presentation/library/anime/AnimeLibrarySettingsDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/anime/AnimeLibraryScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerViewModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/GestureHandler.kt, domain/src/main/java/tachiyomi/domain/library/anime/model/AnimeLibrarySortMode.kt, i18n/src/main/res/values/strings.xml
Changes
----
- Use the right sort function for anime library
- Title
=> feat(Anime Library): Add Sort by Airing time option

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt, i18n/src/main/res/values/strings-aniyomi.xml
=> feat(doubleTapSkip): Add 3 second option

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/components/Seekbar.kt
The aniskip pref check was inverted and thumb was too small.
=> fix(aniskip/seekbar): Show stamps and increase thumb size

app/src/main/java/eu/kanade/presentation/components/SettingsItems.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/dialogs/SubtitleSettingsDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/SubtitleSettingsSheet.kt, i18n/src/main/res/values/strings-aniyomi.xml
=> Subtitle settings

app/src/main/java/eu/kanade/domain/track/service/TrackPreferences.kt, app/src/main/java/eu/kanade/presentation/entries/anime/AnimeScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/AnimeScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/AnimeScreenModel.kt, i18n/src/main/res/values/strings-aniyomi.xml
along with a fix to make alwaysUseExternalPlayer a boolean value in screenmodel instead of injecting it.
=> Show next episode's airing time settings toggle

app/build.gradle.kts, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, gradle/androidx.versions.toml
…and possibly android tv remotes
Possibly closes #1090 
not sure tho since its mi
=> feat(player): handle bluetooth device media buttons 

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
This one's for Claude and his 6 digit cult
=> feat(player): Pause player when headset is disconnected

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAdvancedScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt, app/src/main/java/eu/kanade/tachiyomi/Migrations.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/anime/AnimeLibraryUpdateJob.kt
The anime job is now properly scheduled
=> fix(AnimeLibraryUpdate): Worker names, setupTask call and migrations

app/src/main/java/eu/kanade/presentation/more/settings/screen/AdvancedPlayerSettingsScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsSearchScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt, i18n/src/main/res/values/strings-aniyomi.xml
Also move mpv.conf to a nested settings screen.
=> feat(player): Add debanding setting

app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/presentation/entries/EntryToolbar.kt, app/src/main/java/eu/kanade/presentation/entries/anime/AnimeScreen.kt, app/src/main/java/eu/kanade/presentation/entries/manga/MangaScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/home/HomeScreen.kt, domain/src/test/java/tachiyomi/domain/library/model/LibraryFlagsTest.kt, i18n/src/main/res/values/strings-aniyomi.xml, presentation-widget/src/main/java/tachiyomi/presentation/widget/components/anime/UpdatesAnimeWidget.kt
Add extension settings to Anime/Manga screen
Register recent anime updates widget
Fix pressing "View Episodes" crashing app or opening random manga
=> Some QoL features and fixes

app/src/main/java/eu/kanade/tachiyomi/ui/entries/manga/MangaScreenModel.kt
Changes
---
- Title
References
---
- Closes #1148
=> fix(download): Remove double not in ChapterDownloadActions

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerViewModel.kt
=> fix(player): Fix infinite loop in empty video lists

app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/track/AnimeTrackInfoDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/entries/manga/track/MangaTrackInfoDialog.kt
=> fix(tracking):don't show unusable tracking service

app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt
Adding this commit a little bit earlier
=> Avoid blob in webview

app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/subtitle/SubtitleSettingsSheet.kt
=> feat(player): Preview subtitle styling with actual borders for androids ≤ 9

app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/TracksListingSheet.kt
=> fix(player): Audio tracks are shown properly in offline videos

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
Will show seekbar for a little while when seeking chapters, which I think is a good thing.
=> feat(player): use doubleTapSeek for chapter seeking & show seekbar on seek

app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/tachiyomi/ui/deeplink/DeepLinkScreenType.kt, app/src/main/java/eu/kanade/tachiyomi/ui/deeplink/anime/DeepLinkAnimeActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/deeplink/manga/DeepLinkMangaActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
=> fix(app): Don't ignore the anime side in SEARCH/SEND intents + fix intent labels

app/src/main/java/eu/kanade/presentation/entries/components/EntryToolbar.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/manga/extension/details/MangaSourcePreferencesScreen.kt
Add extension setting button 
Fix manga extension setting showing blank
=> fix: Extension setting

README.md
=> update(README): Make it more accurate

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
=> Fix(pip): add receiver flag for A14+

app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt, core/src/main/java/eu/kanade/tachiyomi/network/OkHttpExtensions.kt
Solved error in downloader, now it properly dump the buffer in to storage without filling the heap.
In particular added a a sink and a fixed buffer of 4kB, that will be emitted each time that I write to the sink
Solved error of timeout too small for big files on slow connection.
=> Fix download large files

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAdvancedScreen.kt, core/src/main/java/eu/kanade/tachiyomi/network/DohProviders.kt, core/src/main/java/eu/kanade/tachiyomi/network/NetworkHelper.kt
=> feat(doh): Add LibreDNS

app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt
Fixed some multithreaded download problem that slipped pass in the previous PR
=> fix mt chunk merging

app/build.gradle.kts, app/src/main/java/eu/kanade/domain/ui/UiPreferences.kt, app/src/main/java/eu/kanade/domain/ui/model/NavStyle.kt, app/src/main/java/eu/kanade/domain/ui/model/StartScreen.kt, app/src/main/java/eu/kanade/presentation/library/components/LibraryToolbar.kt, app/src/main/java/eu/kanade/presentation/more/MoreScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAppearanceScreen.kt, app/src/main/java/eu/kanade/presentation/util/Navigator.kt, app/src/main/java/eu/kanade/tachiyomi/Migrations.kt, app/src/main/java/eu/kanade/tachiyomi/ui/history/HistoriesTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/home/HomeScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/anime/AnimeLibraryTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/manga/MangaLibraryTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/more/MoreTab.kt, app/src/main/java/eu/kanade/tachiyomi/ui/updates/UpdatesTab.kt, domain/src/main/java/tachiyomi/domain/library/service/LibraryPreferences.kt, i18n/src/commonMain/resources/MR/base/strings-aniyomi.xml
Changes
---
- Bring back navigation options
- Start screen selection
- Navigation bar order
- Alternate tab in more
- Cleaned up code
- No longer required to restart to see changes
- Enums  
Issues
---
Closes https://github.com/aniyomiorg/aniyomi/issues/1247
=> fix(navigation): Bring back navigation options

app/src/main/java/eu/kanade/domain/track/anime/interactor/RefreshAnimeTracks.kt, app/src/main/java/eu/kanade/domain/track/manga/interactor/RefreshMangaTracks.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/jellyfin/JellyfinApi.kt
Will update local progress based on tracker progress
Also fixes update issue on jellyfin tracker when adding for the first time.
=> feat(tracker): fix tracking for enhanced services

app/src/main/java/eu/kanade/presentation/more/settings/screen/AdvancedPlayerSettingsScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt, i18n/src/commonMain/resources/MR/base/strings.xml
it's here for anyone who wants to use it.
~~made this pr to procrastinate from what i should be doing~~
don't forget to make `vo=gpu` the default in aniyomi-mpv-lib
=> feat(player): Add `gpu-next` to advanced player settings

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/VideoChaptersSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/PlayerControlsView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/components/CurrentChapter.kt, app/src/main/res/layout/player_controls.xml
Also "optimize?" the logic for highlighting the correct chapter in the the chapters sheet
=> feat(player): Show the current chapter in player controls ui

gradle/libs.versions.toml
fixes the crashes happening recently in r7017
=> fix: bump tachiyomi's subsampling library

core/src/main/java/eu/kanade/tachiyomi/network/NetworkPreferences.kt
I have adjusted the user-agent to fix a MAL login issue. Some users have experienced difficulties logging in due to restrictions in the user-agent. This update should resolve the issue and improve the user experience.
=> Fix Login MAL

source-local/src/commonMain/kotlin/tachiyomi/source/local/io/Archive.kt
=> Add some known ext support to localanime

app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/PictureInPictureHandler.kt
=> fix(pip): pip not broadcasting intent in A14+

app/build.gradle.kts, app/src/main/java/eu/kanade/presentation/more/settings/screen/AdvancedPlayerSettingsScreen.kt, app/src/main/java/eu/kanade/tachiyomi/Migrations.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/PlayerPreferences.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/settings/sheets/PlayerSettingsSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/PlayerControlsView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/viewer/PlayerEnums.kt, i18n/src/commonMain/resources/MR/base/strings.xml
Changes
---
- ENUMS
- VideoDebanding
- Inverted Playback Text
- Cleaned up
- Hardware Decoding
- Aspect State
- Player Stats Page
- Removed extra quotes around a couple of strings
---
=> refactor(player): implement more ENUMS

app/src/main/java/eu/kanade/presentation/more/settings/screen/AdvancedPlayerSettingsScreen.kt
=> fix: advanced player settings crash in android ≤ 10

app/src/main/java/eu/kanade/tachiyomi/data/track/jellyfin/JellyfinInterceptor.kt
=> Fix crashing for jellyifn enhanced tracking

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsPlayerScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt, config/detekt/baseline.xml
A few stuff like headers and external subtitles wont work, but abdallah can fix those on his end
=> feat(external-players): add mpvKt

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, i18n/src/commonMain/moko-resources/base/strings.xml
This way, the anime name, episode number, and episode title can easily be used in scripts and conditional auto profiles
=> feat(player): Set mpv's media-title property

app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/AnimeScreenModel.kt
=> fix(animescreen): Fix airing time not showing

app/src/main/java/eu/kanade/tachiyomi/data/download/anime/AnimeDownloader.kt
=> feat(downloader): Copy the file location when using ext downloader

fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/android/en-US/images/icon.png, fastlane/metadata/android/en-US/short_description.txt
https://github.com/aniyomiorg/aniyomi/issues/60
=> Add fastlane

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
=> Fix episode progress not being saved and duplicate tracks

app/src/main/java/eu/kanade/tachiyomi/util/SubtitleSelect.kt
=> Fix subselect not matching two letter language codes

app/src/main/java/eu/kanade/tachiyomi/ui/player/ExternalIntents.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
=> fix: safer intent extra checks

app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/GestureHandler.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/panels/SubtitleSettingsTypographyCard.kt, i18n/src/commonMain/moko-resources/base/strings.xml
* Adds in border style button I somehow missed
* Fixes double tap behaving incorrectly (https://github.com/abdallahmehiz/mpvKt/commit/643291f6ace434a4c33039676ed87e44cb108d1f and https://github.com/abdallahmehiz/mpvKt/commit/b65ac89dc7c5f117d4b69e7ad03c65676447b877)
=> Small player fixes

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerViewModel.kt
* Fix episode list in player not respecting filters
* Fix crash that can happen if user exits the player whilst stuff is loading
=> fix(player): Fix two issues

app/src/main/java/eu/kanade/tachiyomi/ui/player/controls/components/sheets/ScreenshotSheet.kt
=> fix(player): Don't unpause on share and save

app/src/main/java/eu/kanade/presentation/more/settings/PreferenceItem.kt, app/src/main/java/eu/kanade/presentation/more/settings/widget/EditTextPreferenceWidget.kt
=> fix(prefs): Don't format mpv preferences

app/src/main/java/eu/kanade/tachiyomi/ui/player/AniyomiMPVView.kt
Closes #1882
seems to probably be another issue, but might not
=> fix(mpvlib): Fix npe issues

app/src/main/java/eu/kanade/tachiyomi/ui/player/PlayerActivity.kt
=> fix(player): Fix some issues caused by `10e28cc`

app/src/main/java/eu/kanade/tachiyomi/ui/library/anime/AnimeLibraryScreenModel.kt
Changes
---
- Hopefully fixes the TimSort contract violation caused by AiringTime in the AnimeLibrary
=> fix: AiringTime TimSort contract violation

.github/ISSUE_TEMPLATE/report_issue.yml, .github/ISSUE_TEMPLATE/request_feature.yml, CHANGELOG.md, app/build.gradle.kts, app/src/main/java/mihon/core/migration/migrations/VideoOrientationMigration.kt
Hopefully fix an issue with video orientation migration. Unable to replicate the issue but this should fix it.
=> Fix crash on migration

CHANGELOG.md, domain/src/main/java/tachiyomi/domain/items/episode/service/EpisodeRecognition.kt
=> fix(episoderecognition): Fix episode number parsing

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupDecoder.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupDetector.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/create/BackupCreator.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/models/Backup.kt
Detection for old backups may not be perfect, but should be good enough
=> Move aniyomi specific backup fields to separate proto numbers

app/src/main/java/eu/kanade/tachiyomi/ui/entries/anime/AnimeScreenModel.kt, data/src/main/sqldelightanime/dataanime/animes.sq, data/src/main/sqldelightanime/migrations/133.sqm, data/src/main/sqldelightanime/view/animeseasonstatsView.sq, domain/src/main/java/tachiyomi/domain/entries/anime/interactor/NetworkToLocalAnime.kt, source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/animesource/online/AnimeHttpSource.kt
=> Fix issues regarding seasons
